src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 160)]
    private ?string $title = null;

    #[ORM\Column(length: 162)]
    private ?string $title_slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $text = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $article_date_created = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $article_date_posted = null;

    #[ORM\Column]
    private ?bool $published = null;

    /**
     * @var Collection<int, Section>
     */
    #[ORM\ManyToMany(targetEntity: Section::class, inversedBy: 'articles')]
    private Collection $sections;

    /**
     * @var Collection<int, Tag>
     */
    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'articles')]
    private Collection $tags;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'article')]
    private Collection $comments;

    public function __construct()
    {
        $this->sections = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getTitleSlug(): ?string
    {
        return $this->title_slug;
    }

    public function setTitleSlug(string $title_slug): static
    {
        $this->title_slug = $title_slug;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): static
    {
        $this->text = $text;

        return $this;
    }

    public function getArticleDateCreated(): ?\DateTimeInterface
    {
        return $this->article_date_created;
    }

    public function setArticleDateCreated(\DateTimeInterface $article_date_created): static
    {
        $this->article_date_created = $article_date_created;

        return $this;
    }

    public function getArticleDatePosted(): ?\DateTimeInterface
    {
        return $this->article_date_posted;
    }

    public function setArticleDatePosted(?\DateTimeInterface $article_date_posted): static
    {
        $this->article_date_posted = $article_date_posted;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): static
    {
        $this->published = $published;

        return $this;
    }

    /**
     * @return Collection<int, Section>
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): static
    {
        if (!$this->sections->contains($section)) {
            $this->sections->add($section);
        }

        return $this;
    }

    public function removeSection(Section $section): static
    {
        $this->sections->removeElement($section);

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): static
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(Tag $tag): static
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }
}

src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $article_id = null;

    #[ORM\Column]
    private ?int $user_id = null;

    #[ORM\Column(nullable: true)]
    private ?int $parent_id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $comment_date_created = null;

    #[ORM\Column]
    private ?bool $visible = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?Article $article = null;

    #[ORM\Column(length: 512)]
    private ?string $comment_text = null;

    #[ORM\Column(length: 255)]
    private ?string $comment_username = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArticleId(): ?int
    {
        return $this->article_id;
    }

    public function setArticleId(int $article_id): static
    {
        $this->article_id = $article_id;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getParentId(): ?int
    {
        return $this->parent_id;
    }

    public function setParentId(?int $parent_id): static
    {
        $this->parent_id = $parent_id;

        return $this;
    }

    public function getCommentDateCreated(): ?\DateTimeInterface
    {
        return $this->comment_date_created;
    }

    public function setCommentDateCreated(\DateTimeInterface $comment_date_created): static
    {
        $this->comment_date_created = $comment_date_created;

        return $this;
    }

    public function isVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): static
    {
        $this->visible = $visible;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): static
    {
        $this->article = $article;

        return $this;
    }

    public function getCommentText(): ?string
    {
        return $this->comment_text;
    }

    public function setCommentText(string $comment_text): static
    {
        $this->comment_text = $comment_text;

        return $this;
    }

    public function getCommentUsername(): ?string
    {
        return $this->comment_username;
    }

    public function setCommentUsername(string $comment_username): static
    {
        $this->comment_username = $comment_username;

        return $this;
    }
}

src/Entity/Section.php
<?php

namespace App\Entity;

use App\Repository\SectionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SectionRepository::class)]
class Section
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $section_title = null;

    #[ORM\Column(length: 105)]
    private ?string $section_slug = null;

    #[ORM\Column(length: 500)]
    private ?string $section_detail = null;

    /**
     * @var Collection<int, Article>
     */
    #[ORM\ManyToMany(targetEntity: Article::class, mappedBy: 'sections')]
    private Collection $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSectionTitle(): ?string
    {
        return $this->section_title;
    }

    public function setSectionTitle(string $section_title): static
    {
        $this->section_title = $section_title;

        return $this;
    }

    public function getSectionSlug(): ?string
    {
        return $this->section_slug;
    }

    public function setSectionSlug(string $section_slug): static
    {
        $this->section_slug = $section_slug;

        return $this;
    }

    public function getSectionDetail(): ?string
    {
        return $this->section_detail;
    }

    public function setSectionDetail(string $section_detail): static
    {
        $this->section_detail = $section_detail;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->addSection($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            $article->removeSection($this);
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_USERNAME', fields: ['username'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $username = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 150)]
    private ?string $fullname = null;

    #[ORM\Column(length: 60)]
    private ?string $uniqid = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    #[ORM\Column]
    private ?bool $activate = null;

    /**
     * @var Collection<int, Article>
     */
    #[ORM\OneToMany(targetEntity: Article::class, mappedBy: 'user')]
    private Collection $articles;

    #[ORM\Column(length: 255)]
    private ?string $img_loc = null;

    #[ORM\Column(length: 255)]
    private ?string $quote = null;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFullname(): ?string
    {
        return $this->fullname;
    }

    public function setFullname(string $fullname): static
    {
        $this->fullname = $fullname;

        return $this;
    }

    public function getUniqid(): ?string
    {
        return $this->uniqid;
    }

    public function setUniqid(string $uniqid): static
    {
        $this->uniqid = $uniqid;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function isActivate(): ?bool
    {
        return $this->activate;
    }

    public function setActivate(bool $activate): static
    {
        $this->activate = $activate;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setUser($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getUser() === $this) {
                $article->setUser(null);
            }
        }

        return $this;
    }

    public function getImgLoc(): ?string
    {
        return $this->img_loc;
    }

    public function setImgLoc(string $img_loc): static
    {
        $this->img_loc = $img_loc;

        return $this;
    }

    public function getQuote(): ?string
    {
        return $this->quote;
    }

    public function setQuote(string $quote): static
    {
        $this->quote = $quote;

        return $this;
    }
}

templates/main/_comment.form.twig
<!-- component -->
    <div class="w-full bg-white p-8 rounded-lg shadow-md">
        <form>
            <!-- Post Content Section -->
            <div class="mb-6">
                <label for="postContent" class="block text-gray-700 text-sm font-bold mb-2">Post Comment:</label>
                <textarea id="postContent" name="postContent" rows="4" class="w-full border-2 rounded-md px-4 py-2 leading-5 transition duration-150 ease-in-out sm:text-sm
          sm:leading-5 resize-none focus:outline-none focus:border-blue-500" placeholder="Got something to say about this article?"></textarea>
            </div>
            <!-- Submit Button and Character Limit Section -->
            <div class="flex items-center justify-between">
                <button type="submit" class="flex justify-center items-center bg-blue-800 hover:bg-blue-600 focus:outline-none focus:shadow-outline-blue text-white py-2 px-4 rounded-md transition duration-300 gap-2"> Post <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 24 24" id="send" fill="#fff">
                        <path fill="none" d="M0 0h24v24H0V0z"></path>
                        <path d="M3.4 20.4l17.45-7.48c.81-.35.81-1.49 0-1.84L3.4 3.6c-.66-.29-1.39.2-1.39.91L2 9.12c0 .5.37.93.87.99L17 12 2.87 13.88c-.5.07-.87.5-.87 1l.01 4.61c0 .71.73 1.2 1.39.91z"></path>
                    </svg>
                </button>
                <span class="text-gray-500 text-sm">Max 280 characters</span>
            </div>
        </form>
    </div>

templates/main/_navbar.twig
    <nav class="w-full py-4 bg-blue-800 shadow">
        <div class="w-full container mx-auto flex flex-wrap items-center justify-between">
            {% block navMain %}
                <nav>
                    <ul class="flex items-center justify-between font-bold text-sm text-white uppercase no-underline">
                        {% if is_granted("IS_AUTHENTICATED") %}
                            <li><a class="hover:text-gray-200 hover:underline px-4" href="{{ path("app_logout") }}">Logout</a></li>
                        {% else %}
                            <li><a class="hover:text-gray-200 hover:underline px-4" href="{{ path("app_login") }}">Login</a></li>
                            <li><a class="hover:text-gray-200 hover:underline px-4" href="{{ path('public_user_new') }}">Signup</a></li>
                        {% endif %}
                    </ul>
                </nav>
            {% endblock %}
            {% block navSide %}
                <div class="flex items-center text-lg no-underline text-white pr-6">
                    <a class="" href="#" title="Decorative Link">
                        <i class="fab fa-facebook"></i>
                    </a>
                    <a class="pl-6" href="#" title="Decorative Link">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="pl-6" href="#" title="Decorative Link">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="pl-6" href="#" title="Decorative Link">
                        <i class="fab fa-linkedin"></i>
                    </a>
                </div>
            {% endblock %}
        </div>
    </nav>

templates/main/_pagination.twig
{# NEED TO FIGURE OUT HOW TO APPLY THIS TO PRETTY UP MY PAGINATION #}
<div class="flex items-center py-8">
    {# Previous Page Link #}
    {% if pagination.previousPageNumber is defined %}
        <a href="{{ path(app.request.attributes.get('_route'), app.request.query.all|merge({'page': pagination.previousPageNumber})) }}"
           class="h-10 w-10 font-semibold text-gray-800 hover:bg-blue-600 hover:text-white text-sm flex items-center justify-center">
            Previous
        </a>
    {% endif %}

    {# Page Number Links #}
    {% for page in pagination.pagesInRange %}
        <a href="{{ path(app.request.attributes.get('_route'), app.request.query.all|merge({'page': page})) }}"
           class="h-10 w-10 {{ page == pagination.currentPageNumber ? 'bg-blue-800 text-white' : 'text-gray-800 hover:bg-blue-600 hover:text-white' }} font-semibold text-sm flex items-center justify-center">
            {{ page }}
        </a>
    {% endfor %}

    {# Next Page Link #}
    {% if pagination.nextPageNumber is defined %}
        <a href="{{ path(app.request.attributes.get('_route'), app.request.query.all|merge({'page': pagination.nextPageNumber})) }}"
           class="h-10 w-10 font-semibold text-gray-800 hover:bg-blue-600 hover:text-white text-sm flex items-center justify-center ml-3">
            Next <i class="fas fa-arrow-right ml-2"></i>
        </a>
    {% endif %}
</div>

templates/main/public.article.html.twig
{% extends 'main/public.main.html.twig' %}

{% block content %}
<div class="container mx-auto flex flex-wrap py-6">

    <!-- Post Section -->
    <section class="w-full md:w-2/3 flex flex-col items-center px-3">

        <article class="flex flex-col shadow my-4">
            <!-- Article Image -->
            <a href="{{ path('public_author', { id: article.user.id }) }}" class="hover:opacity-75">
                {% set imgSrc = article.user.imgLoc starts with 'http' ? article.user.imgLoc : asset(article.user.imgLoc) %}
                <img src="{{ imgSrc }}" alt="{{ article.user.fullname }}">
            </a>
            <div class="bg-white flex flex-col justify-start p-6">
                <div class="flex  justify-center gap-8">
                {% for section in artSections %}
                    <button class="rounded-md bg-blue-800 py-2 px-4 border border-transparent text-center text-sm text-white transition-all shadow-md hover:shadow-lg focus:bg-green-700 focus:shadow-none active:bg-green-700 hover:bg-green-700 ml-2">
                        <a href="{{ path('public_section', {slug: section.sectionSlug}) }}">{{ section.sectionTitle }}</a>
                    </button>
                {% endfor %}
                </div>
                <div class="flex  justify-center gap-6 mt-4">
                    {% if is_granted("ROLE_ADMIN") %}
                        <a href="{{ path('app_article_edit', {id: article.id}) }}">
                            <button class="rounded-md bg-blue-800 py-2 px-4 border border-transparent text-center text-sm text-white transition-all shadow-md hover:shadow-lg focus:bg-green-700 focus:shadow-none active:bg-green-700 hover:bg-green-700 ml-2">
                                Edit
                            </button>
                        </a>
                    {% endif %}
                </div>
                <p class="text-3xl font-bold hover:text-gray-700 pb-4">{{ article.title }}</p>
                <p class="text-sm pb-8">
                    By <a href="{{ path('public_author', { id: article.user.id }) }}" class="font-semibold hover:text-gray-800">{{ article.user.fullname }}</a>, Published on {{ article.articleDatePosted | date('F j, Y') }}
                </p>
                <p class="pb-3">{{ article.text }}</p>
            </div>
        </article>

        <div class="w-full flex pt-6">
            <a href="{{ path('public_article', { slug: prev_art.titleSlug, id: prev_art.id }) }}" class="w-1/2 bg-white shadow hover:shadow-md text-left p-6">
                <p class="text-lg text-blue-800 font-bold flex items-center"><i class="fas fa-arrow-left pr-1"></i> Previous</p>
                <p class="pt-2">{{ prev_art.title }}</p>
            </a>
            <a href="{{ path('public_article', { slug: next_art.titleSlug, id: next_art.id }) }}" class="w-1/2 bg-white shadow hover:shadow-md text-right p-6">
                <p class="text-lg text-blue-800 font-bold flex items-center justify-end">Next <i class="fas fa-arrow-right pl-1"></i></p>
                <p class="pt-2">{{ next_art.title }}</p>
            </a>
        </div>


        <div class="w-full text-center md:text-left md:flex-row shadow bg-white mt-10 mb-10 p-6">
                <h5 class="text-xl mr-2 block">Comments </h5>
            {% if comments|length == 0 %}
                 <p>There are no comments for this article</p>
            {% endif %}
            {% for comment in comments %}
                <div class="mb-6">
                    by <span>{{ comment.commentUsername }}, on {{ comment.commentDateCreated | date("F j, Y") }}</span>
                    <p class="my-4">{{ comment.commentText }}</p>
                    <hr>
                </div>
            {% endfor %}
        </div>

        {% if is_granted("IS_AUTHENTICATED") %}
        {% include "main/_comment.form.twig" %}
        {% endif %}


        <div class="w-full flex flex-col text-center md:text-left md:flex-row shadow bg-white mt-10 mb-10 p-6">
            <div class="w-full md:w-1/5 flex justify-center md:justify-start pb-4">
                {% set imgSrc = article.user.imgLoc starts with 'http' ? article.user.imgLoc : asset(article.user.imgLoc) %}
                <a href="{{ path("public_author", { id: article.user.id }) }}">
                    <img src="{{ imgSrc }}" alt="{{ article.user.fullname }}" class="rounded-full shadow h-32 w-32">
                </a>
            </div>
            <div class="flex-1 flex flex-col justify-center md:justify-start">
                <p class="font-semibold text-2xl">{{ article.user.fullname }}</p>
                <p class="pt-2">{{ article.user.quote }}</p>
                <div class="flex items-center justify-center md:justify-start text-2xl no-underline text-blue-800 pt-4">
                    <a class="" href="#" title="Decorative Link">
                        <i class="fab fa-facebook"></i>
                    </a>
                    <a class="pl-4" href="#" title="Decorative Link">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="pl-4" href="#" title="Decorative Link">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="pl-4" href="#" title="Decorative Link">
                        <i class="fab fa-linkedin"></i>
                    </a>
                </div>
            </div>
        </div>

    </section>
    {% block sideBar %}{{ parent() }}test{% endblock %}
</div>
{% endblock %}

templates/main/public.author.html.twig
{% extends "main/public.main.html.twig" %}

{% block content %}
    <h2 class="font-bold text-gray-800 uppercase hover:text-gray-600 text-3xl text-center">{{ author.fullname }}</h2>
    {% if articleCount > 0 %}
    <h4 class="font-bold text-gray-800 uppercase hover:text-gray-600 text-1xl text-center">{{ articleCount }} Article{% if articleCount > 1 %}s{% endif %}</h4>
    {% else %}
        <h4 class="font-bold text-gray-800 uppercase hover:text-gray-600 text-1xl text-center">Has not written any articles....Yet!</h4>
    {% endif %}

    {{ parent() }}
{% endblock %}

templates/main/public.main.html.twig
{% extends "template.html.twig" %}

{% block content %}
    {% if errorMessage is defined and errorMessage is not null %}
        <h3 class="text-center text-3xl font-semibold text-red-500">{{ errorMessage }}</h3>
    {% endif %}
    <div class="container mx-auto flex flex-wrap py-6">
        <!-- Posts Section -->
        <section class="w-full md:w-2/3 flex flex-col items-center px-3">
            {% block posts %}
                <div class="pagination">
                    {{ knp_pagination_render(pagination) }}
                </div>
                {% for article in pagination.items %}
                    <article class="flex flex-col shadow my-4 w-full">
                        <!-- Article Image -->
                        <div class="bg-white flex flex-col justify-start p-6">
                            <div class="flex flex-row items-center gap-8">
                                <a href="{{ path("public_author", {id : article.user.id}) }}" class="hover:opacity-75">
                                    {% set imgSrc = article.user.imgLoc starts with 'http' ? article.user.imgLoc : asset(article.user.imgLoc) %}
                                    <img src="{{ imgSrc }}" alt="missing image" class="h-32 w-32">
                                </a>
                                <a href="{{ path('public_article', {slug: article.titleSlug, id: article.id}) }}" class="text-3xl font-bold hover:text-gray-700 pb-4 text-center pt-20">{{ article.title }}</a>
                            </div>
                            <p class="text-sm pb-3">
                                By <a href="{{ path('public_author', { id: article.user.id }) }}" class="font-semibold hover:text-gray-800">{{ article.user.fullname }}</a>, Published on {{ article.articleDatePosted | date("F j, Y") }}
                            </p>
                            {% set truncateText = article.text|length > 300 ? article.text|slice(0, 300) : article.text %}
                            {% set lastSpace = truncateText|split(' ')|length - 1 %}
                            {% set truncatedWords = truncateText|split(' ')|slice(0, lastSpace)|join(' ') %}
                            {% set finalText = truncatedWords ~ '...' %}
                            <a href="{{ path('public_article', { slug: article.titleSlug, id: article.id}) }}" class="pb-6">{{ finalText }}</a>
                            <a href="{{ path('public_article', { slug: article.titleSlug, id: article.id}) }}" class="uppercase text-gray-800 hover:text-black">Continue Reading <i class="fas fa-arrow-right"></i></a>
                        </div>
                    </article>
                {% endfor %}

                <div class="pagination">
                    {{ knp_pagination_render(pagination) }}
                </div>

                {#
                <div class="flex items-center py-8">
                    <a href="#" class="h-10 w-10 bg-blue-800 hover:bg-blue-600 font-semibold text-white text-sm flex items-center justify-center">1</a>
                    <a href="#" class="h-10 w-10 font-semibold text-gray-800 hover:bg-blue-600 hover:text-white text-sm flex items-center justify-center">2</a>
                    <a href="#" class="h-10 w-10 font-semibold text-gray-800 hover:text-gray-900 text-sm flex items-center justify-center ml-3">Next <i class="fas fa-arrow-right ml-2"></i></a>
                </div>
                #}



            {% endblock %}
        </section>
        {% block sideBar %}{{ parent() }}{% endblock %}
    </div>
    {% block footerCar %}{% endblock %}
{% endblock %}

templates/main/public.section.html.twig
{% extends "main/public.main.html.twig" %}

{% block content %}

    <h2 class="font-bold text-gray-800 uppercase hover:text-gray-600 text-3xl pt-4 text-center">{{ section.sectionTitle }}</h2>
    {{ parent() }}
{% endblock %}